name: Golang Build and Release Windows

on:
  release:
    types: [published]

env:
  BUILD_NAME: TCP_Websocket_Adapter
  
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.0'

    - name: Create Go Build
      run: sudo go build -o ./build/${{env.BUILD_NAME}}
      
    - name: Copy Config and README
      run: |
        sudo cp "Config.json" "./build/Config.json"
        sudo cp "README.md" "./build/README.md"

    - name: Zip Docs and Build
      run: |
        cd build
        sudo zip -r ${{env.BUILD_NAME}}.zip ./*

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./build/${{env.BUILD_NAME}}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
