name: Gloang Build and Release Windows

on:
  release:
    types: [published]
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.0'

    - name: Create Go Build
      run: |
        sudo mkdir build
        go build -o /build/Go_TCP_Websocket_Adapter
      
    - uses: actions/checkout@master
    - name: Copy Config and README
      run: |
        cp "Config.json" "/build/Config.json"
        cp "README.md" "/build/README.md"

    - name: Zip Docs and Build
      uses: TheDoctor0/zip-release@0.7.6
      with:
       path: /build/* # File to add to the archive
       Filename: Go_TCP_Websocket_Adapter.zip # The name of the archive file

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Go_TCP_Websocket_Adapter.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
